import sys
from tkinter import END, INSERT, IntVar, Menu, Tk, Toplevel
from tkinter.scrolledtext import ScrolledText
from tkinter.ttk import *
from tkinter.filedialog import asksaveasfile as filesave, askopenfile
from os.path import exists
from os import mkdir
from getpass import getuser
import base64
icon = b'Qk02MAAAAAAAADYAAAAoAAAAQAAAAEAAAAABABgAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
icon_ = base64.b64decode(icon)
f = open(f"C:/Users/{getuser()}/AppData/Local/Temp/icon.ico", "wb")
f.write(icon_)
f.close()
win=Tk()
win.withdraw()
win.title("Brainfuck IDE")
win.iconbitmap(f"C:/Users/{getuser()}/AppData/Local/Temp/icon.ico")
win.resizable(0, 0)
if not exists(f"C:/Users/{getuser()}/AppData/Local/BFC/settings.txt"):
    mkdir(f"C:/Users/{getuser()}/AppData/Local/BFC")
    with open(f"C:/Users/{getuser()}/AppData/Local/BFC/settings.txt", "w") as f:
        f.write("10")
def print_(text):
    output.configure(state="normal")
    output.insert(END, text)
    output.configure(state="disabled")
def clear(s=None):
    output.configure(state="normal")
    output.delete("1.0", END)
    output.configure(state="disabled")
def input():
    inp.configure(state="normal")
    inp.delete(0, 'end')
    while len(inp.get()) == 0:
        win.update()
    inp.configure(state="disabled")
    return inp.get()
def exit_():
    if codeinp.get("1.0", END) != "\n":
        save()
    with open(f"C:/Users/{getuser()}/AppData/Local/BFC/settings.txt", "w") as f:
        f.write(mode)
    win.destroy()
    sys.exit()
saved = 0
fpath = ""
def new(a=None):
    global saved
    if codeinp.get("1.0", END) != "\n":
        save()
    saved = 0
    clear()
    codeinp.delete("1.0", END)
def save(a=None):
    global saved
    if saved == 0:
        global fpath
        temp = filesave(defaultextension='.bf', filetypes=[("Brainfuck Files", "*.bf"), ("Text files", "*.txt")])
        if temp is not None:
            f = open(temp.name, "w")
            fpath = temp.name
            f.write(codeinp.get("1.0", END))
            f.close()
            saved = 1
    else:
        f = open(fpath, "w")
        f.write(codeinp.get("1.0", END))
        f.close()
    return
def open_(a=None):
    if codeinp.get("1.0", END) != "\n":
        save()
    temp = askopenfile(defaultextension='.bf', filetypes=[("Brainfuck Files", "*.bf"), ("Text files", "*.txt"), ("All files", "*.*")])
    if temp is not None:
        f = open(temp.name, "r")
        codeinp.delete("1.0", END)
        codeinp.insert(INSERT, f.read())
        f.close()
run = 0
def evaluate(z=None):
    if codeinp.get("1.0", END) != "\n":
        save()
        code = codeinp.get("1.0", END)
        global run
        run = 1
        code = cleanup(list(code))
        bracemap = []
        cells, codeptr, cellptr = [0], 0, 0
        while codeptr < len(code):
            if run == 1:
                command = code[codeptr]
                if command == ">":
                    cellptr += 1
                if cellptr == len(cells): cells.append(0)
                if command == "<":
                    cellptr = 0 if cellptr <= 0 else cellptr - 1
                if command == "+":
                    cells[cellptr] = cells[cellptr] + 1 if cells[cellptr] < 255 else 0
                if command == "-":
                    cells[cellptr] = cells[cellptr] - 1 if cells[cellptr] > 0 else 255
                if command == "[":
                    bracemap.append(codeptr)
                if command == "]":
                    if cells[cellptr] == 0:
                        bracemap.pop()
                    else:
                        codeptr = bracemap[-1]
                if command == ".": print_(chr(cells[cellptr]))
                if command == ",": cells[cellptr] = ord(input())
                codeptr += 1
                win.update()
            else:
                break
        stop()
def help(f=None):
    w = Toplevel(win)
    w.title("Help")
    w.resizable(0, 0)
    Label(w, text="""Help:
1. Brainfuck
+   : increase cell value
-   : decrease cell value
<   : move left
>   : move right (can be used infinitely because the cells are dynamic)
[   : enter loop
]   : exit loop if current cell is 0, otherwise go to the last [
.   : print_ the ascii of the current cell (chr(cell))
,   : input 1 char (input())
          
2. Hotkeys:
ctrl-1 : save
ctrl-2 : new
ctrl-3 : open
ctrl-4 : run
ctrl-5 : stop
ctrl-6 : clear code
ctrl-7 : clear console""").grid(column=0, row=0)
    w.mainloop()

def settings(a=None):
    global darkmode, keybind
    w = Toplevel(win)
    w.title("Settings")
    w.resizable(0, 0)
    darkmode_btt = Radiobutton(w, text="Enable dark mode", variable=darkmode, value=True)
    darkmode_btt_2 = Radiobutton(w, text="Disable dark mode", variable=darkmode, value=False)
    darkmode_btt.grid(column=0, row=0)
    darkmode_btt_2.grid(column=0, row=1)
    darkmode_btt = Radiobutton(w, text="Enable keybinds", variable=keybind, value=True)
    darkmode_btt_2 = Radiobutton(w, text="Disable keybinds", variable=keybind, value=False)
    darkmode_btt.grid(column=0, row=2)
    darkmode_btt_2.grid(column=0, row=3)
    btt = Button(w, text="Apply", command=lambda: updatesettings(keybind, darkmode))
    btt.grid(column=0, row=4)
    w.mainloop()

def cleanup(code):
  return ''.join(filter(lambda x: x in ['.', ',', '[', ']', '<', '>', '+', '-'], code))
def stop(a=None):
   global run
   run = 0
mode = open(f"C:/Users/{getuser()}/AppData/Local/BFC/settings.txt", "r").read()
def updatesettings(settings):
    global mode
    keybindings_enabled = settings[0] == "1"
    dark_mode_enabled = settings[1] == "1"
    mode = ""
    if not keybindings_enabled:
        win.unbind_all("<Control-Key-1>")
        win.unbind_all("<Control-Key-2>")
        win.unbind_all("<Control-Key-3>")
        win.unbind_all("<Control-Key-4>")
        win.unbind_all("<Control-Key-5>")
        win.unbind_all("<Control-Key-6>")
        win.unbind_all("<Control-Key-7>")
        mode += "0"
    else:
        win.bind_all("<Control-Key-1>", save)
        win.bind_all("<Control-Key-2>", new)
        win.bind_all("<Control-Key-3>", open_)
        win.bind_all("<Control-Key-4>", evaluate)
        win.bind_all("<Control-Key-5>", stop)
        win.bind_all("<Control-Key-6>", clearcode)
        win.bind_all("<Control-Key-7>", clear)
        mode += "1"
    if dark_mode_enabled:
        win.configure(background="black")
        codeinp.configure(background="black", foreground="white")
        inp.configure(background="black", foreground="white")
        output.configure(background="black", foreground="white")
        mode += "1"
    else:
        win.configure(background="white")
        codeinp.configure(background="white", foreground="black")
        inp.configure(background="white", foreground="black")
        output.configure(background="white", foreground="black")
        mode += "0"
def clearcode(a=None):
    codeinp.delete("1.0", END)
keybind = IntVar(value=int(mode[0]))
darkmode = IntVar(value=int(mode[1]))
codeinp = ScrolledText(width=150, height=30)
codeinp.grid(column=0, row=0, columnspan=2)
inp = Entry(width=5)
inp.grid(column=0, row=1)
inp.configure(state="disabled")
output = ScrolledText(width=145, height=15)
output.grid(column=1, row=1)
output.configure(state="disabled")
menu = Menu(win)
win.configure(menu=menu)
file = Menu(menu, tearoff="off")
file.add_command(label="New", underline=0, command=new)
file.add_command(label="Save", underline=0, command=save)
file.add_command(label="Open...", underline=0, command=open_)
file.add_command(label="Exit", underline=0, command=exit_)
code = Menu(menu, tearoff="off")
code.add_command(label="Run", underline=0, command=evaluate)
code.add_command(label="Stop", underline=0, command=stop)
code.add_command(label="Clear code", underline=0, command=clearcode)
code.add_command(label="Clear console", underline=0, command=clear)
menu.add_cascade(label="File", menu=file)
menu.add_cascade(label="Code", menu=code)
tools = Menu(menu, tearoff="off")
tools.add_command(label="Help", underline=0, command=help)
tools.add_command(label="Settings", underline=0, command=settings)
menu.add_cascade(label="Tools", menu=tools)
win.bind_all("<Control-Key-1>", save)
win.bind_all("<Control-Key-2>", new)
win.bind_all("<Control-Key-3>", open_)
win.bind_all("<Control-Key-4>", evaluate)
win.bind_all("<Control-Key-5>", stop)
win.bind_all("<Control-Key-6>", lambda: codeinp.delete("1.0", END))
win.bind_all("<Control-Key-7>", clear)
updatesettings(mode)
win.protocol("WM_DELETE_WINDOW", exit_)
if len(sys.argv) > 1:
    f_ = open(sys.argv[1], "r")
    codeinp.insert(INSERT, f_.read())
    f_.close()
    saved = 1
    fpath = sys.argv[1]
win.deiconify()
win.mainloop()