from tkinter import Tk, END, INSERT, Toplevel, Label, Radiobutton, Button, IntVar, Menu, Text
from tkinter.messagebox import askyesno
from tkinter.filedialog import asksaveasfile as filesave, askopenfile
from tkinter.scrolledtext import ScrolledText
import sys
from pyperclip import copy
from os.path import dirname, abspath, exists
from base64 import b64decode
win= Tk()
win.withdraw()
win.rowconfigure(0, weight=1)
win.columnconfigure(0, weight=1)
win.title("Brainfuck IDE")
if getattr(sys, "frozen", False):
    script = sys._MEIPASS
else:
    script = dirname(abspath(__file__))
if not script.endswith("\\"):
    script += "\\"
open(script + "icon.ico", "wb").write(b64decode(b'Qk02MAAAAAAAADYAAAAoAAAAQAAAAEAAAAABABgAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiAAAAAAAA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAzEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiAAAAAAAA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAzEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiAAAAAAAA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAzEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6KIA6KIA6KIAAAAAAAAAzEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiAAAAAAAA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAzEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiAAAAAAAA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAzEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiTLEiAAAAAAAA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIA6KIAAAAAAAAAAAAAAAAAAAAAzEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/zEg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//J3//J3//J3//J3//J3//J3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//J3//J3//J3//J3//J3//J3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//J3//J3//J3//J3//J3//J3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//J3//J3//J3//J3//J3//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//J3//J3//J3//J3//J3//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//J3//J3//J3//J3//J3//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAJ3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAPL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//J3//J3//J3//J3//J3//J3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//J3//J3//J3//J3//J3//J3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ3//J3//J3//J3//J3//J3//J3//J3//J3//J3//J3//AAAAAAAAAAAAAAAAAAAAAPL/APL/APL/APL/APL/APL/APL/APL/APL/APL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'))
win.iconbitmap(script + "icon.ico")
if not exists(script + "settings.txt"):
    with open(script + "settings.txt", "w") as f:
        f.write("10")
def print_(text):
    output.configure(state="normal")
    output.insert(END, text)
    output.see(END)
    output.configure(state="disabled")
def clear(s=None):
    output.configure(state="normal")
    output.delete("1.0", END)
    output.configure(state="disabled")
def input():
    inp.configure(state="normal")
    inp.delete("1.0", END)
    while len(inp.get("1.0", END)) == 1:
        win.update()
        if run == 0:
            inp.config(state="disabled")
            return
    inp.configure(state="disabled")
    return inp.get("1.0", END)[0]
def exit_():
    if codeinp.get("1.0", END) != "\n":
        save()
    win.destroy()
    sys.exit()
saved = 0
fpath = ""
def new(a=None):
    global saved, code_
    if codeinp.get("1.0", END) != "\n":
        save()
    saved = 0
    clear()
    codeinp.delete("1.0", END)
    win.title("Brainfuck IDE")
    code_ = "\n"
    check()
def save(a=None):
    global saved
    global fpath
    global code_
    if saved == 0:
        if a is None:
            if askyesno("Brainfuck IDE", "Do you want to save the file?"):
                temp = filesave(defaultextension='.bf', filetypes=[("Brainfuck Files", "*.bf"), ("Text files", "*.txt")])
                if temp is not None:
                    f = open(temp.name, "w")
                    fpath = temp.name
                    f.write(codeinp.get("1.0", END)[:-1])
                    f.close()
                    saved = 1
                    win.title("Brainfuck IDE: " + fpath)
        else:
            temp = filesave(defaultextension='.bf', filetypes=[("Brainfuck Files", "*.bf"), ("Text files", "*.txt")])
            if temp is not None:
                f = open(temp.name, "w")
                fpath = temp.name
                f.write(codeinp.get("1.0", END)[:-1])
                f.close()
                saved = 1
                win.title("Brainfuck IDE: " + fpath)
    else:
        f = open(fpath, "w")
        f.write(codeinp.get("1.0", END)[:-1])
        code_ = codeinp.get("1.0", END)
        f.close()
        win.title("Brainfuck IDE: " + fpath)
    code_ = codeinp.get("1.0", END)
    check()
    return
code_ = "\n"
def open_(a=None):
    global fpath, saved, code, code_
    if codeinp.get("1.0", END) != "\n":
        save()
    temp = askopenfile(defaultextension='.bf', filetypes=[("Brainfuck Files", "*.bf"), ("Text files", "*.txt"), ("All files", "*.*")])
    if temp is not None:
        f = open(temp.name, "r")
        fpath = temp.name
        codeinp.delete("1.0", END)
        codeinp.insert(INSERT, f.read())
        code = f.read()
        code_ = f.read()
        f.close()
        saved = 1
    save()
    win.title("Brainfuck IDE: " + fpath)
    check()
run = 0
def evaluate(z=None):
    global run
    print_("\nProgram running.\n")
    if codeinp.get("1.0", END) != "\n":
        try:
            save()
            code = codeinp.get("1.0", END)
            run = 1
            code = cleanup(list(code))
            bracemap = []
            cells, codeptr, cellptr = [0], 0, 0
            while codeptr < len(code):
                if run == 1:
                    command = code[codeptr]
                    if command == ">":
                        cellptr += 1
                    if cellptr == len(cells): cells.append(0)
                    if command == "<":
                        cellptr = 0 if cellptr <= 0 else cellptr - 1
                    if command == "+":
                        cells[cellptr] += 1
                        cells[cellptr] %= 256

                    if command == "-":
                        cells[cellptr] -= 1
                        cells[cellptr] %= 256
                    if command == "[":
                        bracemap.append(codeptr)
                    if command == "]":
                        if cells[cellptr] == 0:
                            bracemap.pop()
                        else:
                            codeptr = bracemap[-1]
                    if command == ".": print_(chr(cells[cellptr]))
                    if command == ",": cells[cellptr] = ord(input())
                    codeptr += 1
                    win.update()
                else:
                    print_("Program halted.")
                    return
            print_("\nProgram finished.")
        except Exception as e:
            stop()
            print_("\nAn exception has occurred. Details: " + str(e))
            return
        stop()
def help(f=None):
    w = Toplevel(win)
    w.withdraw()
    w.iconbitmap(script + "icon.ico")
    w.title("Help")
    w.resizable(0, 0)
    Label(w, text="""Help:
    1. Brainfuck
        + : increase cell value
        - : decrease cell value
        < : move left
        > : move right (can be used infinitely because the cells are dynamic)
        [ : enter loop
        ] : exit loop if current cell is 0, otherwise go to the last [
        . : print_ the ascii of the current cell (chr(cell))
        , : input 1 char (input())
        Anything else (including space and newline) is a comment   
    2. Hotkeys:
        ctrl-s: save
        ctrl-n: new
        ctrl-o: open
        ctrl-r: run
        ctrl-shift-s: stop
        ctrl-shift-c: clear console
        ctrl-b: text to brainfuck
        ctrl-h: help""", bg="#303030", fg="white", font=("Consolas", 10), anchor="w", justify="left").grid(column=0, row=0)
    w.deiconify()
    w.mainloop()
def cleanup(code):
  return ''.join(filter(lambda x: x in ['.', ',', '[', ']', '<', '>', '+', '-'], code))
def stop(a=None):
   global run
   run = 0
def clearcode(a=None):
    codeinp.delete("1.0", END)
def check():
    if code_ != codeinp.get("1.0", END):
        if not win.title().endswith(" *"):
            win.title(win.title() + " *")
    else:
        win.after(1, check)
def fact(num):
    res = []
    for i in range(1, num + 1, 1):
        if num % i == 0: res.append(i)
    return tuple(res)
def StrToBrf(v):
    #x*y
    #>x[<y>-]<.[-]
    res = ""
    for i in v:
        i = ord(i)
        facts = fact(i)
        middle = len(facts) / 2
        if middle % 1 == 0:
            res += f">{"+" * facts[int(middle) - 1]}[<{"+" * facts[int(middle)]}>-]<.[-]"
        else:
            res += f">{"+" * facts[int(middle - .5)]}[<{"+" * facts[int(middle - .5)]}>-]<.[-]"
    return res
def texttobrainfuck(s=None):
    w=Toplevel(win)
    w.title("Text to Brainfuck")
    w.resizable(0, 0)
    w.iconbitmap(script + "icon.ico")
    text = ScrolledText(w, width=30, height=10, bg="#303030", fg="white", font=("Consolas", 10))
    text.grid(column=0, row=0, columnspan=2)
    out = ScrolledText(w, width=30, height=10, bg="#303030", fg="white", font=("Consolas", 10))
    out.grid(column=0, row=1, columnspan=2)
    out.config(state="disabled")
    def strtobrf(a):
        out.delete("1.0", END)
        res = StrToBrf(a)
        out.config(state="normal")
        out.insert(END, res)
        out.see(END)
        out.config(state="disabled")
    Button(w, text="Copy", command=lambda: copy(out.get("1.0", END)), width=15, bg="#303030", fg="white", font=("Consolas", 10)).grid(column=0, row=2)
    Button(w, text="Convert", command=lambda: strtobrf(text.get("1.0", END)[:-1]), width=15, bg="#303030", fg="white", font=("Consolas", 10)).grid(column=1, row=2)
    w.mainloop()
keybind = IntVar(value=1)
codeinp = ScrolledText(width=200, height=30, bg="#303030", fg="white", font=("Consolas", 10))
codeinp.grid(column=0, row=0, sticky="ewns")
inp = Text(width=200, height=1, bg="#303030", fg="white", font=("Consolas", 10))
inp.grid(column=0, row=2, sticky="ew")
inp.configure(state="disabled")
output = ScrolledText(width=200, height=15, bg="#303030", fg="white", font=("Consolas", 10))
output.grid(column=0, row=1, sticky="ew")
output.configure(state="disabled")
menu = Menu(bg="#303030", fg="white", font=("Consolas", 10))
file = Menu(menu, tearoff="off", bg="#303030", fg="white", font=("Consolas", 10))
file.add_command(label="New", underline=0, command=new)
file.add_command(label="Save", underline=0, command=lambda: save(1))
file.add_command(label="Open...", underline=0, command=open_)
file.add_command(label="Exit", underline=0, command=exit_)
code = Menu(menu, tearoff="off", bg="#303030", fg="white", font=("Consolas", 10))
code.add_command(label="Run", underline=0, command=evaluate)
code.add_command(label="Stop", underline=0, command=stop)
code.add_command(label="Clear console", underline=0, command=clear)
menu.add_cascade(label="File", menu=file)
menu.add_cascade(label="Code", menu=code)
tools = Menu(menu, tearoff="off", bg="#303030", fg="white", font=("Consolas", 10))
tools.add_command(label="Help", underline=0, command=help)
tools.add_command(label="Text to Brainfuck", underline=0, command=texttobrainfuck)
menu.add_cascade(label="Tools", menu=tools)
win.configure(menu=menu)
win.bind_all("<Control-s>", save)
win.bind_all("<Control-n>", new)
win.bind_all("<Control-o>", open_)
win.bind_all("<Control-r>", evaluate)
win.bind_all("<Control-Shift-S>", stop)
win.bind_all("<Control-Shift-C>", clear)
win.bind_all("<Control-b>", texttobrainfuck)
win.bind_all("<Control-h>", help)
win.protocol("WM_DELETE_WINDOW", exit_)
if len(sys.argv) > 1:
    f_ = open(sys.argv[1], "r")
    codeinp.insert(INSERT, f_.read())
    code_ = f_.read()
    win.title("Brainfuck IDE: " + sys.argv[1])
    f_.close()
    saved = 1
    fpath = sys.argv[1]
    save()
win.deiconify()
win.after(10, check)
win.mainloop()